tag_names = [
  'Live Music',
  'Theater Performance',
  'Comedy Show',
  'Dance Performance',
  'Film Screening',
  'Art Exhibit',
  'Open Mic Night',
  'Children’s Theater',
  'Trivia / Game Night',
  'Holiday Celebration',
  'Farmers Market',
  'Craft Fair',
  'Flea Market',
  'Vendor Fair',
  'Holiday Market',
  'Yard Sale',
  'Food Festival',
  'Wine Tasting',
  'Brewery Event',
  'Pop-Up Dinner',
  'Food Truck Rally',
  'Networking Event',
  'Business Meetup',
  'Conference',
  'Seminar / Workshop',
  'Panel Discussion',
  'Game Night',
  'Gala Event',
  'Fundraiser',
  'Charity Walk / Run',
  'Donation Drive',
  'Volunteer Opportunity',
  'Community Cleanup',
  'Town Hall Meeting',
  'Public Lecture',
  'Marathon / Race',
  'Group Hike',
  'Yoga Class',
  'Team Sports',
  'Outdoor Bootcamp',
  'Community Bike Ride',
  'Block Party',
  'Family Fun Day',
  'Kids Workshop',
  'Storytime',
  'Petting Zoo',
  'DIY Workshop',
  'Arts & Crafts Class',
  'Photography Class',
  'Cooking Class',
  'Language Class'
]

tag_names.each do |name|
  Tag.find_or_create_by!(name: name)
end
